(function() {var implementors = {};
implementors["digest"] = [];
implementors["ed25519_dalek"] = [];
implementors["ripemd"] = [];
implementors["ripemd160"] = [];
implementors["sha1"] = [];
implementors["sha2"] = [];
implementors["sha3"] = [];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()